### ISSUE TITLE
获取不到通过xpath定位的元素

### ISSUE THREAD

**Issue by xianyiLuo** [openatx/facebook-wda#103]
Traceback (most recent call last):
File "test_case/test_ios.py", line 58, in
ios.test_step2()
File "test_case/test_ios.py", line 24, in test_step2
self.driver.xpath('//Window[1]/Other[1]/Other[1]/Other[1]/Other[1]/Other[1]/Other[3]/Button[1]/StaticText[1]').click()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 1516, in click
e = self.get(timeout=timeout)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 1478, in get
"timeout %.1f" % timeout)
wda.exceptions.WDAElementNotFoundError: ('element not found', 'timeout 10.0')

iOS版本:13.1.3
xcode版本:11.3.1
wda:0.3.0

**Comment by codeskyblue** [comment]
wda的版本不太对。pip3 uninstall wda  && pip3 install facebook-wda

**Comment by xianyiLuo** [comment]
更新成facebook-wda:1.3.4 
还是一样的报错

**Comment by xianyiLuo** [comment]
更新facebook-wda到最新版:1.3.4
看起来是部分xpath能够获取到，部分不能

**Comment by xianyiLuo** [comment]
找到原因了，需要用iOS的className作为节点才能生效
