### ISSUE TITLE
usb 方式运行wda error较多时，wda自动退出

### ISSUE THREAD

**Issue by dani20210201** [openatx/facebook-wda#105]
Traceback (most recent call last):
INTERNALERROR> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 191, in wrap_session
    self._target(*self._args, **self._kwargs)
  File "/Users/danicawu/Documents/git/iOSchecklist/YSPiOSCheckList/TestCases/test_underlying.py", line 370, in run
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
    pytest.main(["-s", "test_underlying.py::TestPid",
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 247, in _main
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 124, in main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
    ret = config.hook.pytest_cmdline_main(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>     return outcome.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    return outcome.get_result()
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    raise ex[1].with_traceback(ex[2])
INTERNALERROR>     res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 272, in pytest_runtestloop
    res = hook_impl.function(*args)
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return wrap_session(config, _main)
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 228, in wrap_session
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    config.hook.pytest_sessionfinish(
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>     return outcome.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    gen.send(outcome)
INTERNALERROR>     res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/terminal.py", line 717, in pytest_sessionfinish
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 85, in pytest_runtest_protocol
    outcome.get_result()
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 100, in runtestprotocol
    raise ex[1].with_traceback(ex[2])
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 188, in call_and_report
    res = hook_impl.function(*args)
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 80, in pytest_sessionfinish
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    session._setupstate.teardown_all()
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 335, in teardown_all
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    self._pop_and_teardown()
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 310, in _pop_and_teardown
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._teardown_with_finalization(colitem)
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 328, in _teardown_with_finalization
INTERNALERROR>     gen.send(outcome)
    self._callfinalizers(colitem)
INTERNALERROR>   File "/Users/danicawu/Documents/git/iOSchecklist/YSPiOSCheckList/TestCases/conftest.py", line 115, in pytest_runtest_makereport
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 325, in _callfinalizers
INTERNALERROR>     BasePage(session).screenshots('断言失败')
    raise exc
INTERNALERROR>   File "/Users/danicawu/Documents/git/iOSchecklist/YSPiOSCheckList/Utils/basepage.py", line 23, in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/runner.py", line 318, in _callfinalizers
INTERNALERROR>     if self.session.app_current()['bundleId'] != "com.cctv.yangshipin.app.iphone":
    fin()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 338, in app_current
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/fixtures.py", line 878, in finish
INTERNALERROR>     return self.http.get("/wda/activeAppInfo").value
    raise exc
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 196, in fetch
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/fixtures.py", line 871, in finish
INTERNALERROR>     return self._fetch_with_autofix(method, url, data)
    func()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 201, in _fetch_with_autofix
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/fixtures.py", line 800, in _teardown_yield_fixture
INTERNALERROR>     return httpdo(target_url, method, data)
    next(it)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 126, in httpdo
  File "/Users/danicawu/Documents/git/iOSchecklist/YSPiOSCheckList/TestCases/conftest.py", line 70, in session
INTERNALERROR>     return _unsafe_httpdo(url, method, data)
    session.close()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 834, in close
    return self._session_http.delete('/')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 196, in fetch
    return self._fetch_with_autofix(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 201, in _fetch_with_autofix
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 126, in httpdo
    return _unsafe_httpdo(url, method, data)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 147, in _unsafe_httpdo
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/__init__.py", line 147, in _unsafe_httpdo
INTERNALERROR>     response = request_session.request(method,
    response = request_session.request(method,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
INTERNALERROR>     resp = self.send(prep, **send_kwargs)
    r = adapter.send(request, **kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
INTERNALERROR>     r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
INTERNALERROR>     resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
INTERNALERROR>     httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in request
INTERNALERROR>     conn.request(method, url, **httplib_request_kw)
    self._send_request(method, url, body, headers, encode_chunked)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1286, in _send_request
INTERNALERROR>     self._send_request(method, url, body, headers, encode_chunked)
    self.endheaders(body, encode_chunked=encode_chunked)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1286, in _send_request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1235, in endheaders
INTERNALERROR>     self.endheaders(body, encode_chunked=encode_chunked)
    self._send_output(message_body, encode_chunked=encode_chunked)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1235, in endheaders
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1006, in _send_output
INTERNALERROR>     self._send_output(message_body, encode_chunked=encode_chunked)
    self.send(msg)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1006, in _send_output
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 946, in send
INTERNALERROR>     self.send(msg)
    self.connect()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 946, in send
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/requests_usbmux.py", line 52, in connect
INTERNALERROR>     self.connect()
    conn = _device.create_inner_connection(int(port))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Ve  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/usbmux.py", line 249, in create_inner_connection
    raise MuxConnectError("device port:{} is not ready".format(_original_port))
rsions/3.8/lib/python3.8/site-packages/wda/requests_usbmux.py", line 52, in connect
wda.usbmux.MuxConnectError: device port:8100 is not ready
INTERNALERROR>     conn = _device.create_inner_connection(int(port))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wda/usbmux.py", line 249, in create_inner_connection
INTERNALERROR>     raise MuxConnectError("device port:{} is not ready".format(_original_port))
INTERNALERROR> wda.usbmux.MuxConnectError: device port:8100 is not ready

**Comment by gffguo** [comment]
我也有！我以为是我别的工具引起的

**Comment by TangSir61** [comment]
'Connection aborted.', MuxConnectError('device port:8100 is not ready'))同问题，运行一段时间就存在这个问题
