### ISSUE TITLE
请问下，下面的这个报错是啥原因？我是在windows环境上进行执行的

### ISSUE THREAD

**Issue by pxrgod** [openatx/facebook-wda#114]
Traceback (most recent call last):
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "E:\python 3.9.0\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "E:\python 3.9.0\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "E:\python 3.9.0\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "E:\python 3.9.0\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "E:\python 3.9.0\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "E:\python 3.9.0\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\MobileTerminal\IOS_StressTool\testcase\fundStaff\view_channel.py", line 78, in <module>
    view_channel(q, bundle_id, repeat_times)
  File "F:\MobileTerminal\IOS_StressTool\testcase\fundStaff\view_channel.py", line 55, in view_channel
    query.scroll("up")
  File "F:\MobileTerminal\IOS_StressTool\service\query.py", line 222, in scroll
    self.s.swipe_up()
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\wda\__init__.py", line 976, in swipe_up
    return self.swipe(w // 2, h // 2, w // 2, 1)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\wda\__init__.py", line 954, in swipe
    return self._session_http.post('/wda/dragfromtoforduration', data=data)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\wda\utils.py", line 47, in _inner
    return fn(*args, **kwargs)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\wda\__init__.py", line 460, in _fetch
    response = httpdo(url, method, data, timeout)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\wda\__init__.py", line 130, in httpdo
    return _unsafe_httpdo(url, method, data, timeout)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\wda\__init__.py", line 157, in _unsafe_httpdo
    response = request_session.request(method,
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\panxr33970\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by codeskyblue** [comment]
看起来 8100端口没监听吧

**Comment by pxrgod** [comment]
使用的是usbClient初始化的，这个需要额外再增加什么条件么？发自我的华为手机-------- 原始邮件 --------发件人： codeskyblue ***@***.***>日期： 2021年9月7日周二 下午4:49收件人： openatx/facebook-wda ***@***.***>抄送： pxrgod ***@***.***>, Author ***@***.***>主    题： Re: [openatx/facebook-wda] 请问下，下面的这个报错是啥原因？我是在windows环境上进行执行的 (#114)

看起来 8100端口没监听吧

**Comment by pxrgod** [comment]
> 看起来 8100端口没监听吧

使用了tidevice wdaproxy --port 8100后，还是一样的结果，我想说的是跑了一小会时间后，才突然出现这个错误，连接直接中止了

**Comment by pxrgod** [comment]
> 看起来 8100端口没监听吧

使用了tidevice wdaproxy --port 8100后，还是一样的结果，我想说的是跑了一小会时间后，才突然出现这个错误，连接直接中止了
