### ISSUE TITLE
在Xcode 14.3运行wda click()方法报错：Invalid parameter not satisfying: allAttributesForKey != nil

### ISSUE THREAD

**Issue by ssfanli** [openatx/facebook-wda#132]
最更新了mac系统，发现wda没法用了，报错如下：
```
>>> el = c(label="设置").get()
>>> el
<wda.Element(id="41000000-0000-0000-3700-000000000000")>
>>> el.bounds
Rect(x=221, y=514, width=79, height=105)
>>> el.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 1721, in click
    self._session.click(x, y)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 920, in click
    return self.tap(x, y)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 898, in tap
    return self._session_http.post('/wda/tap/0', dict(x=x, y=y))
  File "/opt/homebrew/lib/python3.9/site-packages/wda/utils.py", line 47, in _inner
    return fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 460, in _fetch
    response = httpdo(url, method, data, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 130, in httpdo
    return _unsafe_httpdo(url, method, data, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/wda/__init__.py", line 186, in _unsafe_httpdo
    raise errCls(status, value)
wda.exceptions.WDAUnknownError: WDARequestError(status=110, value={'error': 'unknown error', 'message': 'Invalid parameter not satisfying: allAttributesForKey != nil'})
```
macos 13.2.1
xcode 14.3

**Comment by ssfanli** [comment]
WDA报错
```
Shell$ curl -X POST -d '{"x": 260, "y": 566}' 'http+usbmux://00008030-000159591490802E:8100/session/CD862EF9-365B-49A4-A2AE-AB078C34774A/wda/tap/0'
Return (267ms): {
  "value" : {
    "error" : "unknown error",
    "message" : "Invalid parameter not satisfying: allAttributesForKey != nil",
    "traceback" : "(\n\t0   CoreFoundation                      0x00000001abfbdc44 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1256516\n\t1   libobjc.A.dylib                     0x00000001abcd80c8 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001abeba75c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 194396\n\t3   Foundation                          0x00000001ac2fb960 672CF0CB-4951-3B91-89DF-55E953AEA00F + 571744\n\t4   XCTAutomationSupport                0x0000000104c83600 -[XCElementSnapshot _fetchSimpleValueForKey:] + 1168\n\t5   XCTAutomationSupport                0x0000000104c85510 -[XCElementSnapshot systemAutomationProperties] + 100\n\t6   XCUIAutomation                      0x0000000104b631c0 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke.19 + 212\n\t7   XCTestCore                          0x00000001049dccf4 +[XCTFuture futureWithDescription:block:] + 108\n\t8   XCUIAutomation                      0x0000000104b62d80 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke_2 + 240\n\t9   XCTestCore                          0x0000000104a02e08 -[XCTContext _runActivityNamed:type:block:] + 196\n\t10  XCTestCore                          0x0000000104a01d20 -[XCTContext runInternalActivityNamed:block:] + 124\n\t11  XCUIAutomation                      0x0000000104b62c40 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke + 204\n\t12  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t13  XCTestCore                          0x0000000104a03430 -[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 80\n\t14  XCUIAutomation                      0x0000000104b62a28 +[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:] + 364\n\t15  XCUIAutomation                      0x0000000104b639f4 -[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:error:] + 1044\n\t16  XCUIAutomation                      0x0000000104b63cfc __70-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:]_block_invoke + 116\n\t17  XCTestCore                          0x0000000104a02e08 -[XCTContext _runActivityNamed:type:block:] + 196\n\t18  XCTestCore                          0x0000000104a01d20 -[XCTContext runInternalActivityNamed:block:] + 124\n\t19  XCUIAutomation                      0x0000000104b63bcc -[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:] + 228\n\t20  XCUIAutomation                      0x0000000104b901c0 -[XCUICoordinate(XCUICoordinateTouchEvents) tap] + 376\n\t21  WebDriverAgentLib                   0x000000010aa9dc68 +[FBElementCommands handleTap:] + 884\n\t22  WebDriverAgentLib                   0x000000010aa2be14 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t23  WebDriverAgentLib                   0x000000010aa17a18 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 408\n\t24  WebDriverAgentLib                   0x000000010aa4e524 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t25  WebDriverAgentLib                   0x000000010aa4f014 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t26  libdispatch.dylib                   0x00000001abc6500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t27  libdispatch.dylib                   0x00000001abc718e0 ED0789CD-8D80-39F4-9651-D8707D9C0337 + 63712\n\t28  libdispatch.dylib                   0x00000001abc6500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t29  libdispatch.dylib                   0x00000001abc70cd8 _dispatch_main_queue_callback_4CF + 968\n\t30  CoreFoundation                      0x00000001abf38e20 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 712224\n\t31  CoreFoundation                      0x00000001abf33b7c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 691068\n\t32  CoreFoundation                      0x00000001abf33098 CFRunLoopRunSpecific + 480\n\t33  Foundation                          0x00000001ac278580 672CF0CB-4951-3B91-89DF-55E953AEA00F + 34176\n\t34  WebDriverAgentLib                   0x000000010aa16860 -[FBWebServer startServing] + 328\n\t35  WebDriverAgentRunner                0x000000010a84f980 -[UITestingUITests testRunner] + 80\n\t36  CoreFoundation                      0x00000001abfc4724 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 1283876\n\t37  CoreFoundation                      0x00000001abe8d280 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 8832\n\t38  XCTestCore                          0x0000000104a2c064 +[XCTFailableInvocation invokeStandardConventionInvocation:completion:] + 64\n\t39  XCTestCore                          0x0000000104a2c01c __90+[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:]_block_invoke_3 + 24\n\t40  XCTestCore                          0x0000000104a2ba54 __81+[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:]_block_invoke + 296\n\t41  XCTestCore                          0x00000001049edb88 +[XCTSwiftErrorObservation observeErrorsInBlock:] + 232\n\t42  XCTestCore                          0x0000000104a2b864 +[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:] + 184\n\t43  XCTestCore                          0x0000000104a2bddc +[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:] + 252\n\t44  XCTestCore                          0x0000000104a2c0d4 +[XCTFailableInvocation invokeInvocation:lastObservedErrorIssue:] + 68\n\t45  XCTestCore                          0x0000000104a1a020 __24-[XCTestCase invokeTest]_block_invoke_2 + 84\n\t46  XCTestCore                          0x00000001049fa4cc -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 76\n\t47  XCTestCore                          0x0000000104a232f0 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 88\n\t48  XCTestCore                          0x0000000104a19fa8 __24-[XCTestCase invokeTest]_block_invoke.78 + 144\n\t49  XCTestCore                          0x00000001049e6d8c -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160\n\t50  XCTestCore                          0x0000000104a19b94 -[XCTestCase invokeTest] + 684\n\t51  XCTestCore                          0x0000000104a1b0e4 __26-[XCTestCase performTest:]_block_invoke.119 + 32\n\t52  XCTestCore                          0x00000001049e6d8c -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160\n\t53  XCTestCore                          0x0000000104a1ac38 __26-[XCTestCase performTest:]_block_invoke.110 + 456\n\t54  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t55  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t56  XCTestCore                          0x0000000104a1a8d0 -[XCTestCase performTest:] + 248\n\t57  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t58  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t59  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160\n\t60  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t61  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t62  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t63  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t64  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188\n\t65  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t66  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t67  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160\n\t68  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t69  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t70  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t71  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t72  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188\n\t73  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t74  XCTestCore                          0x0000000104a05bc8 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t75  XCTestCore                          0x0000000104a05aac __27-[XCTestSuite performTest:]_block_invoke + 160\n\t76  XCTestCore                          0x0000000104a055fc __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t77  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t78  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t79  XCTestCore                          0x0000000104a055a4 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t80  XCTestCore                          0x0000000104a057d8 -[XCTestSuite performTest:] + 188\n\t81  XCTestCore                          0x00000001049d6c5c -[XCTest runTest] + 44\n\t82  XCTestCore                          0x00000001049d84d0 __89-[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:]_block_invoke + 100\n\t83  XCTestCore                          0x0000000104a03344 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t84  XCTestCore                          0x0000000104a03270 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140\n\t85  XCTestCore                          0x00000001049d83cc -[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:] + 252\n\t86  XCTestCore                          0x0000000104a37f98 __72-[XCTExecutionWorker enqueueTestIdentifiersToRun:testIdentifiersToSkip:]_block_invoke_2 + 108\n\t87  XCTestCore                          0x0000000104a380d4 -[XCTExecutionWorker runWithError:] + 100\n\t88  XCTestCore                          0x0000000104a00874 __25-[XCTestDriver _runTests]_block_invoke.188 + 52\n\t89  XCTestCore                          0x00000001049e0654 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 256\n\t90  XCTestCore                          0x0000000104a004d8 -[XCTestDriver _runTests] + 1016\n\t91  XCTestCore                          0x00000001049d7144 _XCTestMain + 84\n\t92  WebDriverAgentRunner-Runner         0x0000000104635d0c -[_XCTRunnerAppDelegate application:didFinishLaunchingWithOptions:] + 0\n\t93  CoreFoundation                      0x00000001abf3907c 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 712828\n\t94  CoreFoundation                      0x00000001abf38800 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 710656\n\t95  CoreFoundation                      0x00000001abf33800 97285ACB-7B21-393A-ABF6-03F1DBB5D2A2 + 690176\n\t96  CoreFoundation                      0x00000001abf33098 CFRunLoopRunSpecific + 480\n\t97  GraphicsServices                    0x00000001b609d534 GSEventRunModal + 108\n\t98  UIKitCore                           0x00000001b00537ac UIApplicationMain + 1940\n\t99  WebDriverAgentRunner-Runner         0x0000000104635ec0 main + 160\n\t100 libdyld.dylib                       0x00000001abdb2f30 326A0541-5D13-3687-97EC-C58FACB384EE + 3888\n)"
  },
  "sessionId" : "CD862EF9-365B-49A4-A2AE-AB078C34774A"
}
```

**Comment by yulin1998** [comment]
解决了吗

**Comment by ssfanli** [comment]
> 解决了吗

https://github.com/appium/WebDriverAgent/issues/683#issuecomment-1505541680
