### ISSUE TITLE
pip install --pre facebook-wda ， how to solve，thanks

### ISSUE THREAD

**Issue by zfx5130** [openatx/facebook-wda#41]
admindeMacBook-Pro:~ admin$ pip install --pre facebook-wda
Collecting facebook-wda
  Using cached facebook_wda-0.2.2.dev1-py2-none-any.whl
Requirement already satisfied: six in ./Library/Python/2.7/lib/python/site-packages (from facebook-wda)
Collecting requests>=2.9.1 (from facebook-wda)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.9.1->facebook-wda)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.9.1->facebook-wda)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.9.1->facebook-wda)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->facebook-wda)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: idna, urllib3, certifi, chardet, requests, facebook-wda
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna'

**Comment by SanlinBlackball** [comment]
can  you tell me how to solve it ？

**Comment by codeskyblue** [comment]
reference this web: https://stackoverflow.com/questions/22570929/installing-python-requests

**Comment by zfx5130** [comment]
@SanlinBlackball  "pip install --pre facebook-wda"  instead to "sudo pip install --pre facebook-wda"

**Comment by zfx5130** [comment]
@codeskyblue thanks

**Comment by SanlinBlackball** [comment]
@zfx5130   
 I found that “pip install --pre facebook-wda --user -U ”  also made it
