### ISSUE TITLE
hide_keyborad not work[RuntimeError: not pass tests, this method is not allowed to use]

### ISSUE THREAD

**Issue by zacard-orc** [openatx/facebook-wda#50]
我在试你给的ReadMe，隐藏键盘报这个错
Traceback (most recent call last):
  File "ba.py", line 47, in <module>
    s.keyboard_dismiss()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wda/__init__.py", line 465, in keyboard_dismiss
    raise RuntimeError("not pass tests, this method is not allowed to use")
RuntimeError: not pass tests, this method is not allowed to use

**Comment by codeskyblue** [comment]
该方法至今不能使用，主要是WDA支持问题，Thanks for raise this issue, but there is nothing can do here.
