### ISSUE TITLE
TypeError: 'PngImageFile' does not have the buffer interface

### ISSUE THREAD

**Issue by bottotl** [openatx/facebook-wda#62]
python -m atx gui -s http://192.168.199.146:8100
2019-06-16 00:03:06.259 DEBUG [tkgui: 412] gui starting(scale: 0.5) ...
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 199, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 195, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 49, in _inner
    return inject(mod.main, pargs)
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 40, in inject
    return func(*args)
  File "/usr/local/lib/python2.7/site-packages/atx/cmds/tkgui.py", line 425, in main
    gui = CropIDE('ATX GUI SN: %s' % serial, ratio=scale, device=d)
  File "/usr/local/lib/python2.7/site-packages/atx/cmds/tkgui.py", line 98, in __init__
    self._init_vars()
  File "/usr/local/lib/python2.7/site-packages/atx/cmds/tkgui.py", line 159, in _init_vars
    self.draw_image(self._device.screenshot())
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/mixin.py", line 404, in screenshot
    screen = self._take_screenshot()
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 174, in _take_screenshot
    img = Image.open(BytesIO(raw_png))
TypeError: 'PngImageFile' does not have the buffer interface

**Comment by bottotl** [comment]
10.15 Beta (19A471t)

**Comment by codeskyblue** [comment]
atx-gui项目已经停止维护，请转向 https://github.com/openatx/weditor 这个项目

**Comment by bottotl** [comment]
```
Traceback (most recent call last):
  File "/Users/jft0m/Code/yingyanshi_test/click.py", line 12, in <module>
    dis = d.display
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 102, in display
    return Display(w*self.scale, h*self.scale)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 114, in scale
    self.__scale = min(self.screenshot().size)/min(wsize)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/mixin.py", line 404, in screenshot
    screen = self._take_screenshot()
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 174, in _take_screenshot
    img = Image.open(BytesIO(raw_png))
TypeError: 'PngImageFile' does not have the buffer interface
```

看样子不是 atx-gui 导致的呢

**Comment by bottotl** [comment]
> atx-gui项目已经停止维护，请转向 https://github.com/openatx/weditor 这个项目

```
Traceback (most recent call last):
  File "/Users/jft0m/Code/yingyanshi_test/click.py", line 12, in <module>
    dis = d.display
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 102, in display
    return Display(w*self.scale, h*self.scale)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 114, in scale
    self.__scale = min(self.screenshot().size)/min(wsize)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/mixin.py", line 404, in screenshot
    screen = self._take_screenshot()
  File "/usr/local/lib/python2.7/site-packages/atx/drivers/ios_webdriveragent.py", line 174, in _take_screenshot
    img = Image.open(BytesIO(raw_png))
TypeError: 'PngImageFile' does not have the buffer interface
```

看样子不是 atx-gui 导致的呢

**Comment by codeskyblue** [comment]
这个是因为facebook-wda的接口返回值更改了
