### ISSUE TITLE
ios真机上运行的问题

### ISSUE THREAD

**Issue by fengxiaoyong** [openatx/facebook-wda#63]
Traceback (most recent call last):
  File "/Users/fengxiaooyong/Documents/百度工作/脚本管理/otatest/iosota.py", line 14, in <module>
    s = c.session(bundle_id)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 304, in session
    res = self.http.post('session', data)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 109, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 115, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 77, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/fengxiaooyong/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

手机是iphone 6 plus  版本是12.3.1，Xcode是10.2.1，facebook-wda   0.2.3
在模拟器上运行没有问题，但是真机上运行就有问题
iproxy 8100 8100 使用的是这个代理 ，请教下大神们

**Comment by codeskyblue** [comment]
可能是端口冲突 `iproxy 8200 8100` 试试，然后 `c = wda.Client("http://localhost:8200")`
