### ISSUE TITLE
AttributeError: 'Client' object has no attribute '_sid'

### ISSUE THREAD

**Issue by ssfanli** [openatx/facebook-wda#94]
# 现象
print(c)时候报错
```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/ssfanli/Myfolder/pyproj/work/YSPTimeConsuming/venv/lib/python3.7/site-packages/wda/__init__.py", line 440, in __str__
    return 'wda.Client (sessionId=%s)' % self._sid
AttributeError: 'Client' object has no attribute '_sid'
```
看了下这快的源码，发现`Client`里面没有`self._sid`属性
```py
    def __str__(self):
        return 'wda.Client (sessionId=%s)' % self._sid
```

**Comment by codeskyblue** [comment]
fixed
